CREATE TABLE SANDWICH_TWEETS.TWEETS
(
TWEET_KEY SERIAL,
ID BIGINT UNIQUE,
TEXT VARCHAR(1024) NOT NULL, --Tweets can only be 280 characters, sometimes special characters can create larger tweets.  
USERNAME VARCHAR(50) NOT NULL,
DATE_TWEETED TIMESTAMP NOT NULL,
INSERT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
